### ISSUE TITLE
mysql to mysql全量+增量

### ISSUE THREAD

**Issue by glkappe** [moiot/gravity#209]
您好，
请问，最新版本支持mysql to mysql，只同步1张表吗。
[input]
type = "mysql"
mode = "replication"

[[input.config.table-configs]]
schema = "test"
table = "tbl1"

其他表我都不要，需要写过滤吗？

**Comment by Ryan-Git** [comment]
写一下[路由](https://github.com/moiot/gravity/blob/master/docs/2.0/04-outputs-en.md)，table config 可以不重复写。比如
```toml
[[output.config.routes]]
match-schema = "test"
match-table = "tbl1"
target-schema = "test_new"
target-table = "tbl_new"
```

**Comment by glkappe** [comment]
感谢回复，@Ryan-Git
再请教一下，
1.[input.config.source]数据源可以配置多个吗。就像mysql的多源复制一样。
2.如果不能我无法启动两个gravity，因为8080被占用（报错如下：
{"level":"fatal","msg":"http error: listen tcp :8080: bind: address already in use","time":"2019-09-20T17:02:07+08:00"}
） 我该如何修改这个端口呢。（我是在弄一台服务器上启动的gravity）

**Comment by Ryan-Git** [comment]
1、这个目前不行，需要起多个进程
2、./gravity -http-addr :8081

**Comment by glkappe** [comment]
非常感谢回复!!!  @Ryan-Git
./gracity -h竟然有提示，sorry，没有认真看。
还有一个问题想请教下：
1.我如何将目前增量的gtid向前设置一些呢，（ps：将当前gtid点4e21ade9-f503-ee17-7bf0-5235f9e704c:1-100 设置为 4e21ade9-f503-ee17-7bf0-f5235f9e704c:1-10)

**Comment by Ryan-Git** [comment]
https://github.com/moiot/gravity/blob/master/docs/2.0/03-inputs-en.md

```toml
#
# The starting position of incremental synchronization
# Empty by default. Synchronization starts from the current the GTID position.
# Optional
#
[input.config.start-position]
binlog-gtid = "abcd:1-123,egbws:1-234"
```

**Comment by glkappe** [comment]
灰常感谢回复~ @Ryan-Git
再请教一个问题：
1.当我[[input.config.table-configs]]为多个的时候，[[output.config.routes]]也要为多个。
input部分可以写出列表形式 但是 out部分就不能写成列表形式。求解？
ps：

[[input.config.table-configs]]
schema = "a"
table = "aa"

[[input.config.table-configs]]
schema = "a"
table = "bb"
-- ----------------

[[output.config.routes]]
match-schema = "a"
match-table = "aa"
target-schema = "a"
target-table = "aa"

[[output.config.routes]]
match-schema = "a"
match-table = "bb"
target-schema = "a"
target-table = "bb"

2. 并且 该配置文件一旦被gravity启动就不能修改了。所以需要很多个配置文件。
3.gravity在output机器上如何设置线程数，在回放replace into时产生了gap lock。所以想设置下。


期待回复

**Comment by Ryan-Git** [comment]
1、没有特殊的需要`input.config.table-configs`可以不设，会从 `routes` 里找出需要同步的表；

`routes` 里的 `target-schema/table` 如果和原表一致可以不设或设为*；

`match-schema` 确实只能一个，`match-table` 可以多个的，详见 [matcher](https://github.com/moiot/gravity/blob/master/docs/2.0/07-matcher-en.md)

2、为什么启动就不能修改了，需要很多个配置文件？gravity 检测到修改会自动退出，需要手动启动。如果是用 docker/systemd 启动的话会自动重启。

3、 建议隔离级别设为 RC，写入时是全字段 replace into，RR 容易有死锁而且很慢。最大并发可按如下设置
```toml
[output.config.target]
max-open = 50
max-idle = 50 ##建议与 max-open 相同，特别是并发较大的情况下
```
