### ISSUE TITLE
想同时同步多个库，如何配置？

### ISSUE THREAD

**Issue by wwwwwwchun** [moiot/gravity#286]
我想同时同步多个MySQL库到MySQL库，麻烦问一下，如何配置
output.config.routes这个参数？

**Comment by Ryan-Git** [comment]
```toml
[[output.config.routes]]
match-schema = "test1"
target-schema = "test1"

[[output.config.routes]]
match-schema = "abc"
target-schema = "abc"
```
