### ISSUE TITLE
全量任务过程中，在源端对同步的表新增字段，同步报错

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#321]
1、配置文件:
```toml
# name 必填
name = "dts_test123"

# 内部用于保存位点、心跳等事项的库名，默认为 _gravity
internal-db-name = "_gravity"

#
# Input 插件的定义，此处定义使用 mysql
#
[input]
type = "mysql"
mode = "batch"
[input.config.source]
host = "192.168.184.34"
username = "root"
password = "root123"
port = 38375

#
# Output 插件的定义，此处使用 mysql
#
[output]
type = "mysql"
[output.config.target]
host = "192.168.184.34"
username = "root"
password = "root"
port = 38723

# 路由规则的定义
[[output.config.routes]]
match-schema = "ywsdb"
match-table = "dts_test_table"
target-schema = "ywsdb"
target-table = "dts_test_table"
```

2、增字段的DDL语句:
测试SQL1:
```sql
alter table dts_test_table add column add_col int default null;
```

测试SQL2:
```sql
 alter table dts_test_table add column add_col int default 5; 
```

均有问题

3、源端加完字段后，同步任务立刻报错，报错信息如下:
{"level":"fatal","msg":"[LoopInBatch] failed to find next start point: sql: expected 12 destination arguments in Scan, not 11\n/Users/database/WorkSpace/go/src/github.com/moiot/gravity/pkg/utils/db.go:179: \n/Users/database/WorkSpace/go/src/github.com/moiot/gravity/pkg/inputs/mysqlbatch/mysql_table_scanner.go:677: \n/Users/database/WorkSpace/go/src/github.com/moiot/gravity/pkg/inputs/mysqlbatch/mysql_table_scanner.go:635: ","time":"2021-09-22T11:10:47+08:00"}
