### ISSUE TITLE
route中增加match-dml-op的问题

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#324]
1、配置文件
```toml
# name 必填
name = "dts_test123"

# 内部用于保存位点、心跳等事项的库名，默认为 _gravity
internal-db-name = "_gravity"

#
# Input 插件的定义，此处定义使用 mysql
#
[input]
type = "mysql"
mode = "replication"
[input.config.source]
host = "192.168.184.34"
username = "root"
password = "new_root_pwd"
port = 38375

[[input.config.table-configs]]
schema = "ywsdb"
table = "dts_test_table_small1"

[input.config]
nr-scanner = 4
table-scan-batch = 10000
batch-per-second-limit = 2
max-full-dump-count = 1000000


#
# Output 插件的定义，此处使用 mysql
#
[output]
type = "mysql"
[output.config.target]
host = "192.168.184.34"
username = "root"
password = "new_root_pwd123"
port = 38723

[output.config]
enable-ddl = true

# 路由规则的定义
[[output.config.routes]]
match-schema = "ywsdb"
match-table = "dts_test_table_small1"
match-dml-op = ["insert", "update", "delete"] 
target-schema = "ywsdb"
target-table = "dts_test_table_small1"
```

问题1: 
任务启动从全量变到增量阶段以后，发现目标表没有数据，删除了配置文件中的: match-dml-op = ["insert", "update", "delete"]  部分，删除_gravity 库中的Job元数据信息，重新启动后，正常同步，为什么加了这个选项会导致数据不会同步过去 ? 

问题2:
最开始配置文件中没加“match-dml-op”，顺利同步到增量阶段后，再修改配置文件 加上了 “match-dml-op” 后，源端执行update,delete,insert 都不同步。
