### ISSUE TITLE
mysql同步到kafka报错

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#327]
配置:
```toml
# name 必填
name = "mysql2kafka.ticket"

internal-db-name = "_gravity"

#
# Input 插件的定义，此处定义使用 mysql
#
[input]
type = "mysql"
mode = "replication"


[input.config.source]
host = "xxxxx"
username = "root"
password = "xxxx
port = 3306

[[input.config.table-configs]]
schema = "ticket"
table = "ticket_2"

[[filters]]
type = "reject"
[filters.config]
match-schema = "_gravity"
match-table= "*"

#
# Output 插件的定义，此处使用 mysql
#
[output]
type = "async-kafka"

[output.config.kafka-global-config]
broker-addrs = ["10.122.1.80:9092","10.122.1.159:9092","10.122.1.205:9092"]
mode = "async"

[[output.config.routes]]
match-schema = "ticket"
match-table = "ticket_2"
dml-topic = "binlog.db.ticket"
```

刚开启同步的时候突然报错

{"level":"fatal","msg":"line 1 column 33 near \"\"audio_quality_case\" (\n  \"id\" bigint(20) NOT NULL COMMENT '主键id',\n  \"audio_id\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '录音ID',\n  \"ticket_id\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '工单ID',\n  \"case_level\" varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '案件评级',\n  \"urge_uid\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '实际催收人员',\n  \"billsec\" int(11) unsigned NOT NULL DEFAULT '0' COMMENT '录音时长',\n  \"call_type\" int(10) unsigned NOT NULL DEFAULT '0' COMMENT '录音类型',\n  \"comment\" varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '催收跟进结果',\n  \"mark_label\" varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '标记标签',\n  \"is_out\" tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '是否出催.1: 已出催; 0: 未出催',\n  \"out_urge_time\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '出催时间',\n  \"urge_user_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '催收员姓名',\n  \"urge_tl_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '催收员TL姓名',\n  \"urge_om_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '催收员OM姓名',\n  \"assign_user_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '质检员姓名',\n  \"assign_tl_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '质检员TL姓名',\n  \"assign_om_name\" varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '质检员OM姓名',\n  \"ctime\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',\n  \"utime\" bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '最后更新时间',\n  PRIMARY KEY (\"id\"),\n  KEY \"idx_audio_id\" (\"audio_id\"),\n  KEY \"idx_ctime\" (\"ctime\"),\n  KEY \"idx_ticket_id\" (\"ticket_id\"),\n  KEY \"idx_urge_uid\" (\"urge_uid\")\n)\" ","time":"2022-01-21T06:20:11-06:00"}
