### ISSUE TITLE
can provide an example for mongodb to tidb/mysql config file?

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#90]
I want to the from mongodb to tidb/mysql ，but I don‘t know how configure it ? Could you provide an example for it.

**Comment by Ryan-Git** [comment]
it's simply a mongo input with mysql output like following, the problem is how would you like to handle nested documents? The data model isn't compatible.

```toml
name = "mongo2mysql"

[input]
type = "mongo"
mode = "stream"

[input.config.source]
host = "127.0.0.1"
port = 27017
username = ""
password = ""

[output]
type = "mysql"

[output.config.target]
host = "127.0.0.1"
username = ""
password = ""
port = 3306

[[output.config.routes]]
match-schema = "test"
match-table = "*"
```
